version: '3.0'
services:
  busybox:
    image: registry.access.redhat.com/ubi8/ubi@sha256:269e9753043a4066af12649e921c6ad3201702fda5b2652f7a4aa010c2ed4c1a
    command: |
      curl -v -X "PUT" "${S3_URL}" -H "Authorization: ${AUTHORIZATION}"  -H "Content-Type: text/plain"  -d @/var/hyperprotect/se-checksums.txt.enc
    volumes:
      - /var/hyperprotect/:/var/hyperprotect/:ro
    environment:
      - AUTHORIZATION
      - S3_URL
